# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - deepo-web

env:
  AZURE_WEBAPP_NAME: deepo-web   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '/Deepo.Client.Web'      # set this to the path to your web app project, defaults to the repository root
  PROJECT_NAME: "Deepo.Client.Web"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          
      - name: Authenticate with GitHub Packages
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.WRITE_PACKAGES_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Check current directory
        run: pwd

      - name: List files in project directory
        run: ls -R "${{ env.PROJECT_NAME }}"
          
      - name: Build with dotnet
        run: dotnet build "${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj" --configuration Release

      - name: dotnet publish
        run: dotnet publish "${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj" -c Release -o "${{ env.DOTNET_ROOT }}/${{ env.AZURE_WEBAPP_NAME }}"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.PROJECT_NAME }}/bin/Release/net9.0

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E6B1FA1C22B94EF98857539F445BFB85 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A77E698740F44A98ABD53397B8B120F1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DF08DE38AEB74678ACF9B186AA6E9941 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'deepo-web'
          slot-name: 'Production'
          package: .
          
